GET http://localhost:8080/users
###
POST http://localhost:8080/user/create
Content-Type: application/json

{
  "email": "email@yandex.com",
  "login": "Nick",
  "name": "test",
  "birthDate": "2001-04-03"
}

###
PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "email": "test@yandex.com",
  "login": "Nick",
  "nickname": "Test",
  "birthdate": "2001-04-03"
}

###
GET http://localhost:8080/films


###
POST http://localhost:8080/film/create
Content-Type: application/json

{
  "name": "nisi eiusmod",
  "description": "adipisicing",
  "releaseDate": "1967-03-25",
  "duration": 100
}

###
PUT http://localhost:8080/film/1
Content-Type: application/json

{
  "name": "Film Updated",
  "releaseDate": "1989-04-17",
  "description": "New film update decription",
  "duration": 190,
  "rate": 4
}